apiVersion: v1
kind: Secret
metadata:
  name: jfrogcred
  namespace: valaxy
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJldmFtcC5qZnJvZy5pbyI6IHsKCQkJImF1dGgiOiAiWkc5amEyVnlYM1Z6WlhJNktqRWpSRzlqYTJWeU1UST0iCgkJfQoJfQp9
type: kubernetes.io/dockerconfigjson